namespace RCL.Features.Calendar.Constants;

public static class FeastDayDates
{
  public static readonly DateTime Hanukkah = Convert.ToDateTime("2025-12-14");
  public static readonly DateTime Purim = Convert.ToDateTime("2026-03-03");
  public static readonly DateTime Passover = Convert.ToDateTime("2026-04-03");
  public static readonly DateTime Weeks = Convert.ToDateTime("2026-05-23");
  public static readonly DateTime Trumpets = Convert.ToDateTime("2026-09-12");
  public static readonly DateTime YomKippur = Convert.ToDateTime("2026-09-21");
  public static readonly DateTime Tabernacles = Convert.ToDateTime("2026-09-26");
}

/*
Generated by KeyDate.tvfFeastDayDatesCodeGen
*/