namespace RCL.Features.Calendar.Constants;

// ToDo: 
public static class FeastDayDates 
{
  //public static readonly DateTime Hanukkah = Convert.ToDateTime("2025-12-14");
  public static readonly DateOnly Purim = DateOnly.Parse("2026-03-03");
  public static readonly DateOnly Passover = DateOnly.Parse("2026-04-03");
  public static readonly DateOnly Weeks = DateOnly.Parse("2026-05-23");
  public static readonly DateOnly Trumpets = DateOnly.Parse("2026-09-12");
  public static readonly DateOnly YomKippur = DateOnly.Parse("2026-09-21");
  public static readonly DateOnly Tabernacles = DateOnly.Parse("2026-09-26");
  public static readonly DateOnly Hanukkah = DateOnly.Parse("2026-12-16");    


  public static IReadOnlyList<DateOnly> List(bool includeMinValue = false)
  {
    var items = new List<DateOnly>
    {
      Purim,
      Passover,
      Weeks,
      Trumpets,
      YomKippur,
      Tabernacles,
      Hanukkah
    };

    if (!includeMinValue)
    {
      items.RemoveAll(d => d == DateOnly.MinValue);
    }

    return items;
  }
}

/*
Generated by KeyDate.tvfFeastDayDatesCodeGen
*/