namespace RCL.Features.Calendar.Constants;

public static class LunarMonthDates // See FN1 
{
  public static readonly DateTime HeshvanPrevGregYrMonth = Convert.ToDateTime("2025-10-12"); // 2025-10-23 - Mo 8
  public static readonly DateTime KislevPrevGregYrMonth = Convert.ToDateTime("2025-11-09"); //2025-11-21 - Mo 9
  public static readonly DateTime TevetPrevGregYrMonth = Convert.ToDateTime("2025-12-10"); //2025-12-21 - Mo 10
  public static readonly DateTime Shevat = Convert.ToDateTime("2026-01-09");  // 2025-01-30 - Mo 11
  public static readonly DateTime Adar = Convert.ToDateTime("2026-02-18");
	public static readonly DateTime Adar2 = DateTime.MinValue; // FN2: Setting to MinValue means there is no Adar II this year
  public static readonly DateTime Nissan = Convert.ToDateTime("2026-03-20");
  public static readonly DateTime Iyar = Convert.ToDateTime("2026-04-18");
  public static readonly DateTime Sivan = Convert.ToDateTime("2026-05-18");
  public static readonly DateTime Tammuz = Convert.ToDateTime("2026-06-16");
  public static readonly DateTime Av = Convert.ToDateTime("2026-07-15");
  public static readonly DateTime Elul = Convert.ToDateTime("2026-08-14");
  public static readonly DateTime Tishri = Convert.ToDateTime("2026-09-12");
  public static readonly DateTime Heshvan = Convert.ToDateTime("2026-10-12");
  public static readonly DateTime Kislev = Convert.ToDateTime("2026-11-10");
  public static readonly DateTime Tevet = Convert.ToDateTime("2026-12-10");

  public static IReadOnlyList<DateTime> List(bool includeMinValue = false)
  {
    var items = new List<DateTime>
    {
      HeshvanPrevGregYrMonth,
      KislevPrevGregYrMonth,
      TevetPrevGregYrMonth,
      Shevat,
      Adar,
      Adar2,
      Nissan,
      Iyar,
      Sivan,
      Tammuz,
      Av,
      Elul,
      Tishri,
      Heshvan,
      Kislev,
      Tevet
    };

    if (!includeMinValue)
    {
      items.RemoveAll(d => d == DateTime.MinValue);
    }

    return items;
  }
}

/* 
### Footnotes
- FN1: Generated by KeyDate.tvfLunarMonthDatesCodeGen.sql  
- FN2: if Adar2 == DateTime.MinValue then there is no Adar II for this year
	- therefore when e.g. looping through the months you need to check if you should filter out skip Adar II
  - e.g. `foreach (var item in LunarMonth.List.Where(w => w.Date > DateTime.MinValue).ToList())`
*/



