namespace RCL.Features.Calendar.Constants;

public static class LunarMonthDates // See FN1 
{
  public static readonly DateOnly HeshvanPrevGregYrMonth = DateOnly.Parse("2025-10-12"); // 2025-10-23 - Mo 8
  public static readonly DateOnly KislevPrevGregYrMonth = DateOnly.Parse("2025-11-09"); //2025-11-21 - Mo 9
  public static readonly DateOnly TevetPrevGregYrMonth = DateOnly.Parse("2025-12-10"); //2025-12-21 - Mo 10
  public static readonly DateOnly Shevat = DateOnly.Parse("2026-01-09");  // 2025-01-30 - Mo 11
  public static readonly DateOnly Adar = DateOnly.Parse("2026-02-18");
	public static readonly DateOnly Adar2 = DateOnly.MinValue; // FN2: Setting to MinValue means there is no Adar II this year
  public static readonly DateOnly Nissan = DateOnly.Parse("2026-03-20");
  public static readonly DateOnly Iyar = DateOnly.Parse("2026-04-18");
  public static readonly DateOnly Sivan = DateOnly.Parse("2026-05-18");
  public static readonly DateOnly Tammuz = DateOnly.Parse("2026-06-16");
  public static readonly DateOnly Av = DateOnly.Parse("2026-07-15");
  public static readonly DateOnly Elul = DateOnly.Parse("2026-08-14");
  public static readonly DateOnly Tishri = DateOnly.Parse("2026-09-12");
  public static readonly DateOnly Heshvan = DateOnly.Parse("2026-10-12");
  public static readonly DateOnly Kislev = DateOnly.Parse("2026-11-10");
  public static readonly DateOnly Tevet = DateOnly.Parse("2026-12-10");

  public static IReadOnlyList<DateOnly> List(bool includeMinValue = false)
  {
    var items = new List<DateOnly>
    {
      HeshvanPrevGregYrMonth,
      KislevPrevGregYrMonth,
      TevetPrevGregYrMonth,
      Shevat,
      Adar,
      Adar2,
      Nissan,
      Iyar,
      Sivan,
      Tammuz,
      Av,
      Elul,
      Tishri,
      Heshvan,
      Kislev,
      Tevet
    };

    if (!includeMinValue)
    {
      items.RemoveAll(d => d == DateOnly.MinValue);
    }

    return items;
  }
}

/* 
### Footnotes
- FN1: Generated by KeyDate.tvfLunarMonthDatesCodeGen.sql  
- FN2: if Adar2 == DateOnly.MinValue then there is no Adar II for this year
	- therefore when e.g. looping through the months you need to check if you should filter out skip Adar II
  - e.g. `foreach (var item in LunarMonth.List.Where(w => w.Date > DateOnly.MinValue).ToList())`
*/



