namespace RCL.Features.Calendar.Constants;

public static class SeasonDates 
{
  //public static readonly DateOnly Winter = DateOnly.Parse("2025-12-21");
  public static readonly DateOnly Spring = DateOnly.Parse("2026-03-17");
  public static readonly DateOnly Summer = DateOnly.Parse("2026-06-20");
  public static readonly DateOnly Fall = DateOnly.Parse("2026-09-22");  //2026-09-26
  public static readonly DateOnly Winter = DateOnly.Parse("2026-12-21");
  public static readonly DateOnly WinterNextYear = DateOnly.Parse("2027-12-20");

  public static IReadOnlyList<DateOnly> List(bool includeMinValue = false)
  {
    var items = new List<DateOnly>
    {
      Spring,
      Summer,
      Fall,
      Winter,
      WinterNextYear
    };

    if (!includeMinValue)
    {
      items.RemoveAll(d => d == DateOnly.MinValue);
    }

    return items;
  }
}

/*
Generated by KeyDate.tvfSeasonDatesCodeGen
*/