namespace RCL.Features.Calendar.Constants;

public static class SeasonDates 
{
  //public static readonly DateTime Winter = Convert.ToDateTime("2025-12-21");
  public static readonly DateTime Spring = Convert.ToDateTime("2026-03-17");
  public static readonly DateTime Summer = Convert.ToDateTime("2026-06-20");
  public static readonly DateTime Fall = Convert.ToDateTime("2026-09-22");  //2026-09-26
  public static readonly DateTime Winter = Convert.ToDateTime("2026-12-21");
  public static readonly DateTime WinterNextYear = Convert.ToDateTime("2027-12-20");

  public static IReadOnlyList<DateTime> List(bool includeMinValue = false)
  {
    var items = new List<DateTime>
    {
      Spring,
      Summer,
      Fall,
      Winter,
      WinterNextYear
    };

    if (!includeMinValue)
    {
      items.RemoveAll(d => d == DateTime.MinValue);
    }

    return items;
  }
}

/*
Generated by KeyDate.tvfSeasonDatesCodeGen
*/