using Ardalis.SmartEnum;
using Microsoft.AspNetCore.Components;
using RCL.Features.Calendar.Constants;

namespace RCL.Features.Calendar.Enums;



public abstract class EventMoon : SmartEnum<EventMoon>
{
  internal const string Adar2Suffix = " II";

  #region Id's
  private static class Id
  {
    internal const int Shevat = 1;
    internal const int Adar = 2;
    internal const int Adar2 = 3;
    internal const int Nissan = 4;
    internal const int Iyar = 5;
    internal const int Sivan = 6;
    internal const int Tammuz = 7;
    internal const int Av = 8;
    internal const int Elul = 9;
    internal const int Tishri = 10;
    internal const int Heshvan = 11;
    internal const int Kislev = 12;
    internal const int Tevet = 13;
  }
  #endregion

  #region Declared Public Instances
  public static readonly EventMoon Nissan = new NissanMonth();
  public static readonly EventMoon Iyar = new IyarMonth();
  public static readonly EventMoon Sivan = new SivanMonth();
  public static readonly EventMoon Tammuz = new TammuzMonth();
  public static readonly EventMoon Av = new AvMonth();
  public static readonly EventMoon Elul = new ElulMonth();
  public static readonly EventMoon Tishri = new TishriMonth();
  public static readonly EventMoon Shevat = new ShevatMonth();
  public static readonly EventMoon Adar = new AdarMonth();
  public static readonly EventMoon Adar2 = new Adar2Month();
  public static readonly EventMoon Heshvan = new HeshvanMonth();
  public static readonly EventMoon Kislev = new KislevMonth();
  public static readonly EventMoon Tevet = new TevetMonth();

  private EventMoon(string name, int value) : base(name, value) { }

  #endregion

  #region Extra Fields
  public abstract int BabylonianSort { get; }  // From Nisan to Adar II
  public abstract int HebrewSort { get; }  // From Nisan to Adar II
  public abstract string FullName { get; }
  public abstract int EventSort { get; }
  public abstract string Hebrew { get; }
  public abstract string BiblicalName { get; }
  public abstract string BiblicalHebrew { get; }  // http://www.yashanet.com/library/hebrew-days-and-months.html
  public abstract string Description { get; }
  public abstract DateOnly? Date { get; } // Code generated by KeyDate.tvfDateCodeGen
  #endregion

  #region Extra Properties
  public DateOnly? ErevDate => Date.HasValue ? Date.Value.AddDays(-1) : (DateOnly?)null;
  public DateOnly? DayTimeDate => Date;  
  public string SpanIcon => $"<span class='badge bg-secondary'><i class='far fa-moon '></i></span>";
  public string SpanText => $"<span class='badge bg-secondary text-white'> {Name}</span>";

  #endregion

  #region Private Instantiation

  private sealed class ShevatMonth : EventMoon
  {
    public ShevatMonth() : base($"{nameof(Id.Shevat)}", Id.Shevat) { }
    public override int BabylonianSort => 11;
    public override int HebrewSort => 5;
    public override int EventSort => 0;
    public override string Hebrew => "שבט";
    public override string BiblicalName => "11th";
    public override string BiblicalHebrew => "";
    public override string FullName => nameof(Id.Shevat);
    public override string Description => String.IsNullOrEmpty(BiblicalHebrew) ? $"{BiblicalName}" : $"{BiblicalName} {BiblicalHebrew}";
    public override DateOnly? Date => LunarMonthDates.Shevat;
  }

  private sealed class AdarMonth : EventMoon
  {
    public AdarMonth() : base($"{nameof(Id.Adar)}", Id.Adar) { }
    public override int BabylonianSort => 12;
    public override int HebrewSort => 6;
    public override int EventSort => 0;
    public override string Hebrew => "אדר א";
    public override string BiblicalName => "12th";
    public override string BiblicalHebrew => "";
    public override string FullName => nameof(Id.Adar);
    public override string Description => String.IsNullOrEmpty(BiblicalHebrew) ? $"{BiblicalName}" : $"{BiblicalName} {BiblicalHebrew}";
    public override DateOnly? Date => LunarMonthDates.Adar;
  }

  private sealed class Adar2Month : EventMoon
  {
    public Adar2Month() : base($"{nameof(Id.Adar2)}", Id.Adar2) { }
    public override int BabylonianSort => 13;
    public override int HebrewSort => 7;
    public override int EventSort => 0;
    public override string Hebrew => "אדר ב";
    public override string BiblicalName => "13th";
    public override string BiblicalHebrew => "";
    public override string FullName => nameof(Id.Adar) + Adar2Suffix;
    public override string Description => String.IsNullOrEmpty(BiblicalHebrew) ? $"{BiblicalName}" : $"{BiblicalName} {BiblicalHebrew}";
    public override DateOnly? Date => null; // ToDo: use this when done refactoring LunarMonthDates.Adar2;
  }

  private sealed class NissanMonth : EventMoon
  {
    public NissanMonth() : base($"{nameof(Id.Nissan)}", Id.Nissan) { }
    public override int BabylonianSort => 1;
    public override int HebrewSort => 8;
    public override int EventSort => 0;
    public override string Hebrew => "ניסן";
    public override string BiblicalName => "Abib";
    public override string BiblicalHebrew => "הָאָבִיב";
    public override string FullName => nameof(Id.Nissan);
    public override string Description => String.IsNullOrEmpty(BiblicalHebrew) ? $"{BiblicalName}" : $"{BiblicalName} {BiblicalHebrew}";
    public override DateOnly? Date => LunarMonthDates.Nissan;
  }

  private sealed class IyarMonth : EventMoon
  {
    public IyarMonth() : base($"{nameof(Id.Iyar)}", Id.Iyar) { }
    public override int BabylonianSort => 2;
    public override int HebrewSort => 9;
    public override int EventSort => 0;
    public override string Hebrew => "אייר";
    public override string BiblicalName => "Ziv";
    public override string BiblicalHebrew => "זִו";
    public override string FullName => nameof(Id.Iyar);
    public override string Description => String.IsNullOrEmpty(BiblicalHebrew) ? $"{BiblicalName}" : $"{BiblicalName} {BiblicalHebrew}";
    public override DateOnly? Date => LunarMonthDates.Iyar;
  }

  private sealed class SivanMonth : EventMoon
  {
    public SivanMonth() : base($"{nameof(Id.Sivan)}", Id.Sivan) { }
    public override int BabylonianSort => 3;
    public override int HebrewSort => 10;
    public override int EventSort => 0;
    public override string Hebrew => "סיון";
    public override string BiblicalName => "3rd";
    public override string BiblicalHebrew => "";
    public override string FullName => nameof(Id.Sivan);
    public override string Description => String.IsNullOrEmpty(BiblicalHebrew) ? $"{BiblicalName}" : $"{BiblicalName} {BiblicalHebrew}";
    public override DateOnly? Date => LunarMonthDates.Sivan;
  }

  private sealed class TammuzMonth : EventMoon
  {
    public TammuzMonth() : base($"{nameof(Id.Tammuz)}", Id.Tammuz) { }
    public override int BabylonianSort => 4;
    public override int HebrewSort => 11;
    public override int EventSort => 0;
    public override string Hebrew => "תמוז";
    public override string BiblicalName => "4th";
    public override string BiblicalHebrew => "";
    public override string FullName => nameof(Id.Tammuz);
    public override string Description => String.IsNullOrEmpty(BiblicalHebrew) ? $"{BiblicalName}" : $"{BiblicalName} {BiblicalHebrew}";
    public override DateOnly? Date => LunarMonthDates.Tammuz;
  }

  private sealed class AvMonth : EventMoon
  {
    public AvMonth() : base($"{nameof(Id.Av)}", Id.Av) { }
    public override int BabylonianSort => 5;
    public override int HebrewSort => 12;
    public override int EventSort => 0;
    public override string Hebrew => "אב";
    public override string BiblicalName => "5th";
    public override string BiblicalHebrew => "";
    public override string FullName => nameof(Id.Av);
    public override string Description => String.IsNullOrEmpty(BiblicalHebrew) ? $"{BiblicalName}" : $"{BiblicalName} {BiblicalHebrew}";
    public override DateOnly? Date => LunarMonthDates.Av;
  }

  private sealed class ElulMonth : EventMoon
  {
    public ElulMonth() : base($"{nameof(Id.Elul)}", Id.Elul) { }
    public override int BabylonianSort => 6;
    public override int HebrewSort => 13;
    public override int EventSort => 0;
    public override string Hebrew => "אלול";
    public override string BiblicalName => "6th";
    public override string BiblicalHebrew => "";
    public override string FullName => nameof(Id.Elul);
    public override string Description => String.IsNullOrEmpty(BiblicalHebrew) ? $"{BiblicalName}" : $"{BiblicalName} {BiblicalHebrew}";
    public override DateOnly? Date => LunarMonthDates.Elul;
  }

  private sealed class TishriMonth : EventMoon
  {
    public TishriMonth() : base($"{nameof(Id.Tishri)}", Id.Tishri) { }
    public override int BabylonianSort => 7;
    public override int HebrewSort => 1;
    public override int EventSort => 0;
    public override string Hebrew => "תשרי";
    public override string BiblicalName => "Ethanim";
    public override string BiblicalHebrew => "הָאֵתָנִים";
    public override string FullName => nameof(Id.Tishri);
    public override string Description => String.IsNullOrEmpty(BiblicalHebrew) ? $"{BiblicalName}" : $"{BiblicalName} {BiblicalHebrew}";
    public override DateOnly? Date => LunarMonthDates.Tishri;
  }


  private sealed class HeshvanMonth : EventMoon
  {
    public HeshvanMonth() : base($"{nameof(Id.Heshvan)}", Id.Heshvan) { }
    public override int BabylonianSort => 8;
    public override int HebrewSort => 2;
    public override int EventSort => 0;
    public override string Hebrew => "חשון";
    public override string BiblicalName => "Bul";
    public override string BiblicalHebrew => "בּוּל";
    public override string FullName => nameof(Id.Heshvan);
    public override string Description => String.IsNullOrEmpty(BiblicalHebrew) ? $"{BiblicalName}" : $"{BiblicalName} {BiblicalHebrew}";
    public override DateOnly? Date => LunarMonthDates.Heshvan;
  }

  private sealed class KislevMonth : EventMoon
  {
    public KislevMonth() : base($"{nameof(Id.Kislev)}", Id.Kislev) { }
    public override int BabylonianSort => 9;
    public override int HebrewSort => 3;
    public override int EventSort => 0;
    public override string Hebrew => "כסלו";
    public override string BiblicalName => "9th";
    public override string BiblicalHebrew => "";
    public override string FullName => nameof(Id.Kislev);
    public override string Description => String.IsNullOrEmpty(BiblicalHebrew) ? $"{BiblicalName}" : $"{BiblicalName} {BiblicalHebrew}";
    public override DateOnly? Date => LunarMonthDates.Kislev;
  }

  private sealed class TevetMonth : EventMoon
  {
    public TevetMonth() : base($"{nameof(Id.Tevet)}", Id.Tevet) { }
    public override int BabylonianSort => 10;
    public override int HebrewSort => 4;
    public override int EventSort => 0;
    public override string Hebrew => "טבת";
    public override string BiblicalName => "10th";
    public override string BiblicalHebrew => "";
    public override string FullName => nameof(Id.Tevet);
    public override string Description => String.IsNullOrEmpty(BiblicalHebrew) ? $"{BiblicalName}" : $"{BiblicalName} {BiblicalHebrew}";
    public override DateOnly? Date => LunarMonthDates.Tevet;
  }
  #endregion
}


