<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\Core\LivingMessiah.ShabbatPdf.Core.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.Configuration.Json" Version="10.0.9" />
    <PackageReference Include="Microsoft.Extensions.Configuration.UserSecrets" Version="10.0.9" />
    <PackageReference Include="Microsoft.Extensions.Hosting" Version="10.0.9" />
    <PackageReference Include="System.CommandLine" Version="2.0.9" />
  </ItemGroup>

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <RootNamespace>LivingMessiah.ShabbatPdf.Cli</RootNamespace>
    <AssemblyName>LivingMessiah.ShabbatPdf.Cli</AssemblyName>
    <UserSecretsId>55d9f8ea-37ff-4a29-8b16-1dc8b9fc5ed2</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <None Update="appsettings.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>

</Project>
