#Requires -Version 5.1
<#
.SYNOPSIS
  Generate SQL batch of dbo.stpDonationInsert calls from the Sukkot Stripe CSV export.

.DESCRIPTION
  Reads CSV from Export-SukkotStripeSessions.ps1 and writes a .sql file you can
  review and run in SSMS against SukkotRegistration.

  Output style (positional args):

    DECLARE @RC int, @NewId int;
    EXECUTE @RC = dbo.stpDonationInsert 42, 25.00, N'Notes', N'test@example.com', N'ReferenceId', N'admin', '2026-08-17', @NewId OUTPUT;

.EXAMPLE
  .\scripts\New-SukkotDonationInsertSql.ps1

.EXAMPLE
  .\scripts\New-SukkotDonationInsertSql.ps1 `
    -CsvPath "$env:USERPROFILE\Downloads\sukkot-stripe-sessions.csv" `
    -OutPath "$env:USERPROFILE\Downloads\sukkot-donation-insert.sql"
#>
[CmdletBinding()]
param(
	[string] $CsvPath = (Join-Path $env:USERPROFILE "Downloads\sukkot-stripe-sessions.csv"),
	[string] $OutPath = (Join-Path $env:USERPROFILE "Downloads\sukkot-donation-insert.sql"),
	[string] $CreatedBy = "admin",
	[string] $Notes = "Stripe Checkout Session Completed (manual backfill)"
)

$ErrorActionPreference = "Stop"

function Escape-NString([string] $value) {
	if ($null -eq $value) { return "" }
	return $value.Replace("'", "''")
}

if (-not (Test-Path -LiteralPath $CsvPath)) {
	throw "CSV not found: $CsvPath. Run Export-SukkotStripeSessions.ps1 first."
}

if ($CreatedBy.Length -gt 25) {
	throw "CreatedBy must be <= 25 characters (dbo.Donation.CreatedBy). Got: '$CreatedBy'"
}

$rows = Import-Csv -LiteralPath $CsvPath
if (-not $rows -or $rows.Count -eq 0) {
	throw "CSV has no rows: $CsvPath"
}

$sb = New-Object System.Text.StringBuilder
[void]$sb.AppendLine("/* Generated by New-SukkotDonationInsertSql.ps1")
[void]$sb.AppendLine("   Source CSV: $CsvPath")
[void]$sb.AppendLine("   Generated:  $([datetime]::UtcNow.ToString('u'))")
[void]$sb.AppendLine("   Review before running against SukkotRegistration.")
[void]$sb.AppendLine("   Tip: skip any RegistrationId that already has dbo.Donation. */")
[void]$sb.AppendLine()
[void]$sb.AppendLine("SET NOCOUNT ON;")
[void]$sb.AppendLine()

$written = 0
$skipped = 0

foreach ($row in $rows) {
	$regId = 0
	if (-not [int]::TryParse([string]$row.RegistrationId, [ref]$regId) -or $regId -le 0) {
		Write-Warning "Skip: invalid RegistrationId='$($row.RegistrationId)'"
		$skipped++
		continue
	}

	$amount = $null
	try {
		$amount = [decimal]::Parse([string]$row.AmountUsd, [cultureinfo]::InvariantCulture)
	}
	catch {
		try {
			$amount = [decimal]([string]$row.AmountUsd)
		}
		catch {
			Write-Warning ("Skip RegistrationId={0} - invalid AmountUsd='{1}'" -f $regId, $row.AmountUsd)
			$skipped++
			continue
		}
	}
	if ($amount -le 0) {
		Write-Warning ("Skip RegistrationId={0} - AmountUsd must be > 0" -f $regId)
		$skipped++
		continue
	}

	$referenceId = [string]$row.ReferenceId
	if ([string]::IsNullOrWhiteSpace($referenceId)) {
		Write-Warning ("Skip RegistrationId={0} - missing ReferenceId" -f $regId)
		$skipped++
		continue
	}

	$email = [string]$row.Email
	if ($null -eq $email) { $email = "" }

	$createDate = [datetime]::UtcNow.Date
	if (-not [string]::IsNullOrWhiteSpace($row.CreatedUtc)) {
		$parsed = [datetime]::MinValue
		if ([datetime]::TryParse([string]$row.CreatedUtc, [ref]$parsed)) {
			$createDate = $parsed.ToUniversalTime().Date
		}
	}
	$createDateSql = $createDate.ToString("yyyy-MM-dd")

	$amountSql = $amount.ToString("0.00", [cultureinfo]::InvariantCulture)
	$notesSql = Escape-NString $Notes
	$emailSql = Escape-NString $email
	$refSql = Escape-NString $referenceId
	$bySql = Escape-NString $CreatedBy

	[void]$sb.AppendLine("/* RegistrationId=$regId  $email  $referenceId */")
	[void]$sb.AppendLine("DECLARE @RC int, @NewId int;")
	[void]$sb.AppendLine("EXECUTE @RC = dbo.stpDonationInsert $regId, $amountSql, N'$notesSql', N'$emailSql', N'$refSql', N'$bySql', '$createDateSql', @NewId OUTPUT;")
	[void]$sb.AppendLine("SELECT @RC AS ReturnCode, @NewId AS NewId, $regId AS RegistrationId;")
	[void]$sb.AppendLine("GO")
	[void]$sb.AppendLine()
	$written++
}

$dir = Split-Path -Parent $OutPath
if ($dir -and -not (Test-Path $dir)) {
	New-Item -ItemType Directory -Path $dir | Out-Null
}

[System.IO.File]::WriteAllText($OutPath, $sb.ToString(), [System.Text.UTF8Encoding]::new($false))
Write-Host "Wrote $written statement(s) to $OutPath (skipped $skipped)"
Write-Host "Open in SSMS and run against SukkotRegistration after review."
