namespace LivingMessiah.Features.Calendar.Constants;

public static class LunarMonthDates // See FN1
{
	public static readonly DateTime HeshvanPrevGregYrMonth = Convert.ToDateTime("2024-10-31");
	public static readonly DateTime KislevPrevGregYrMonth = Convert.ToDateTime("2024-11-30");
	public static readonly DateTime TevetPrevGregYrMonth = Convert.ToDateTime("2025-01-01");
	public static readonly DateTime Shevat = Convert.ToDateTime("2025-01-30");
	public static readonly DateTime Adar = Convert.ToDateTime("2025-03-01");

	/*
	See FN2
	public static readonly DateTime Adar2 = Adar;
	public static readonly DateTime Adar2 = DateTime.MinValue;
	*/
	public static readonly DateTime Adar2 = Convert.ToDateTime("2025-03-02");

	public static readonly DateTime Nissan = Convert.ToDateTime("2025-03-30");
	public static readonly DateTime Iyar = Convert.ToDateTime("2025-04-29");
	public static readonly DateTime Sivan = Convert.ToDateTime("2025-05-28");
	public static readonly DateTime Tammuz = Convert.ToDateTime("2025-06-27");
	public static readonly DateTime Av = Convert.ToDateTime("2025-07-26");
	public static readonly DateTime Elul = Convert.ToDateTime("2025-08-25");
	public static readonly DateTime Tishri = Convert.ToDateTime("2025-09-23");
	public static readonly DateTime Heshvan = Convert.ToDateTime("2025-10-23");
	public static readonly DateTime Kislev = Convert.ToDateTime("2025-11-21");
	public static readonly DateTime Tevet = Convert.ToDateTime("2025-12-21");
}

/* 
### Footnotes
- FN1: Generated by KeyDate.tvfLunarMonthDatesCodeGen.sql  
- FN2: if Adar2 == DateTime.MinValue then there is no Adar II for this year
	- therefore when e.g. looping through the months you need to check if you should filter out skip Adar II
*/



